### ISSUE TITLE
With fresh install SSH keys don't import

### ISSUE THREAD

**Issue by o-leary** [symkat/MeshMage#2]
Following the guide with debian 10 (sudo was not automatically installed).

I have MeshMage up and running but cannot generate or import SSH keys (they never appear in the UI).

I tested the command string for ssh-keygen based on MinionTasks.pm code and this appears to work. Error is permission denied creating /home/symkat.

`grep -rnw '/home/meshmage' -e 'home/symkat'`
`/home/meshmage/MeshMage/Web/meshmage.yml:10:  store: /home/symkat/Code/MeshMage/.nebula
/home/meshmage/MeshMage/Web/meshmage.yml:14:  rundir: /home/symkat/Code/MeshMage/Ansible
/home/meshmage/MeshMage/Web/meshmage.yml:17:  prefix: /home/symkat/Code/MeshMage/data
/home/meshmage/MeshMage/Ansible/roles/meshmage/templates/meshmage.yml.j2:10:  store: /home/symkat/Code/MeshMage/.nebula
/home/meshmage/MeshMage/Ansible/roles/meshmage/templates/meshmage.yml.j2:14:  rundir: /home/symkat/Code/MeshMage/Ansible
/home/meshmage/MeshMage/Ansible/roles/meshmage/templates/meshmage.yml.j2:17:  prefix: /home/symkat/Code/MeshMage/data`

**Comment by symkat** [comment]
If you go to /minion/ you should see the jobs queue, and the import_sshkey and generate_sshkey  jobs might have failing information.

**Comment by o-leary** [comment]
Thank you I have updated the above. I've changed these references to /home/meshmage and rebooted, keys are now generated. There were a number of other tasks failed so I think I may need to redeploy and do this before creating a network.

**Comment by symkat** [comment]
I've updated that template and I think addressed the sudo thing (I suppose its not needed in the readme there since you should already be root).  Let me know if I misunderstood the sudo reference, or you still experience any issues.

https://github.com/symkat/MeshMage/commit/0e8cccb0114eac192027c78b29ea8a01b5e99b29

**Comment by o-leary** [comment]
Awesome, I'll go have a go now. The sudo thing was minor, the Ansible script uses it as meshmage, so it fails without it. I also tried to be cheeky and use the netinstall iso to set up debian, this was ill-advised as perl modules fail to install with the script. Your project looks great, thanks for your hard work :)

**Comment by o-leary** [comment]
I ran this again, there are still file path references in /home/meshmage/MeshMage/Web/meshmage.yml, but no longer in /home/meshmage/MeshMage/Ansible/roles/meshmage/templates/meshmage.yml.j2

Now I can generate SSH keys when I change these and reboot, but I get a file/path error for CA when creating a network. I suspect it is related to these references being present during install, but I don't know because I am noob @ nebula.

```
---
args:
- 4
attempts: 1
children: []
created: 2021-09-20T07:35:31.7693Z
delayed: 2021-09-20T07:35:31.7693Z
expires: ~
finished: 2021-09-20T07:35:31.89702Z
id: 6
lax: 0
notes:
  mesh.mydomain.com: 1
parents: []
priority: 0
queue: default
result: |
  No such file or directory at /home/meshmage/MeshMage/Web/lib/MeshMage/Web/Plugin/MinionTasks.pm line 34.
retried: ~
retries: 0
started: 2021-09-20T07:35:31.77697Z
state: failed
task: create_network_cert
time: 2021-09-20T07:35:35.43668Z
worker: 4

```

relates to

```
        run3( [ $job->app->nebula_cert, 'ca',
            '-out-crt', "$network_path/ca.crt",
            '-out-key', "$network_path/ca.key",
            '-name'   , $network->name,
        ]);
```

/home/meshmage/Code/MeshMage/data/nebula contains empty numbered folders, it appears the ca is missing or misplaced.
